# This file stores the flash_commands for each mcus
# Previous version KCONFIG_CONFIG was needed now it is automaticly added when make flash is called
# version : 0.1
# tested/supported flash methods :
#  - make flash
#  - sdcard_flash
#  - flashtool.py
#  - mount/cp/umount (for rp2040)
 
#[rpi]
#klipper_section: mcu rpi
#action_command: make flash

#[octopus]
#klipper_section: mcu
#action_command: ~/klipper/scripts/flash-sdcard.sh /dev/ttyAMA0 btt-octopus-f446-v1

#[mcu]
#quiet_command: enter_bootloader -u <YOUR_CANBUS_UUID>
#action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_stm32f446xx_<BOARD_ID>-if00

[mcu nhk]
quiet_command: enter_bootloader -t usb -d /dev/serial/by-id/usb-Klipper_rp2040_3136313132019E63-if00
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_rp2040_3136313132019E63-if00

[mcu mmu0]
klipper_section: mcu mmu0
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 6f2631e4346b

[mcu mmu1]
klipper_section: mcu mmu1
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u db4de26e31c4

[mcu mmu2]
klipper_section: mcu mmu2
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 28679fd96d17 

[mcu mmu3]
klipper_section: mcu mmu3
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u aa1b2ad500d7

[mcu mmu4]
klipper_section: mcu mmu4
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u ec59b1cd44a7

[mcu ebb36]
klipper_section: mcu ebb36
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can1 -u 9b3d880c5868

#[mcu Leviathan]
#quiet_command: enter_bootloader -u ba78d0e2dcf8
#action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-Klipper_stm32f446xx_1A003D000451313133353932-if00



